# -*- coding: utf-8 -*-
#
# This file is part of Cookiecutter - Invenio Module Template
# Copyright (C) 2015, 2016, 2017 CERN
# Copyright (C) 2017 ETH Zurich, Swiss Data Science Center.
#
# Cookiecutter - Invenio Module Template is free software; you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# Cookiecutter - Invenio Module Template is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cookiecutter - Invenio Module Template; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307, USA.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

sudo: false

notifications:
  email: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - "travis_retry pip install --upgrade pip"
  - "travis_retry pip install cookiecutter"
  - "travis_retry pip install Sphinx>=1.4.2 sphinx_rtd_theme>=0.1.7"

script:
  - "./run-tests.sh"
